App3D/Inbox/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dm.urls'))
]

App3D/urls.py
from django.urls import path, re_path
from App3D.views import *
from django.contrib.auth.views import LogoutView
UUID_CANAL_REGEX = r'canal/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'

urlpatterns = [
    path('', inicio, name="inicio"),
    path("pages/", leerBlogs, name="leerBlogs"),
    path("pages/<id>", detalleBlog, name="detalleBlog"),



    path('login/', login_request, name='login'),
    path('account/signup', register, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("editarPerfil/", editarPerfil, name='editarPerfil'),
    path("agregarAvatar/", agregarAvatar, name="agregarAvatar"),


    re_path(UUID_CANAL_REGEX, CanalDetailView.as_view()),
	path("dm/<str:username>", mensajes_privados),
	path("ms/<str:username>", DetailMs.as_view(), name="detailms"),
    path("inbox/", Inbox.as_view(), name="inbox"),

]

App3D/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import uuid

from django.apps import apps

from django.db.models import Count

# Create your models here.



class Blog(models.Model):
    Tema= models.CharField(max_length=50)
    Material= models.CharField(max_length=50)
    Escala= models.CharField(max_length=50)

    def __str__(self):
        return self.Tema+" "+self.Escala


class Avatar(models.Model):
    imagen=models.ImageField(upload_to='avatares')
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - {self.imagen}"
    
    
    
    
    
    
    
    
    
    
    
    
    
    
User = settings.AUTH_USER_MODEL

class ModelBase(models.Model):
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)
		if qs.exists():

			return qs.order_by("tiempo").first(), False #obj, created

		User = apps.get_model("auth", model_name='User')
		usuario_a, usuario_b = None, None
		try:
			usuario_a = User.objects.get(username=username_a)
		except User.DoesNotExist:
			return None, False

		try:
			usuario_b = User.objects.get(username=username_b)
		except User.DoesNotExist:
			return None, False

		if usuario_a == None or usuario_b==None:
			return None, False

		
		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=usuario_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=usuario_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b])
		return obj_canal, True

class Canal(ModelBase):
	#como funciona slak
	#1 user
	#2 users
	#2+

	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)

	objects = CanalManager()
    

App3D/templates/App3D/RegistrOk.html
{% extends "App3D/padre.html" %}

{% load static %}

{% block titulo2 %}
<h1 class="mb-5"> {{ mensaje }} </h1>
{% endblock %}

{% block contenido_que_cambia %}
<p class="text-white-30 mb-4">Para loguearte click <a href="{% url 'inicio' %}"style="color: blue;">aca</a></p>            
{% endblock %}

App3D/templates/App3D/base.html
<!DOCTYPE html>
<html>
<head>
	
	{% load static %}     
           
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<title>Imprimiendo3D - Blog de noticias</title>
	<!-- Favicon-->
	<link rel="icon" type="image/png" href="{% static 'App3D/assets/Icono.png' %}">
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="{% static 'App3D/css/styles.css' %}" rel="stylesheet" />
	<title>
		Dm
	</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

		*{
			margin: 0;
			padding: 0;
		}

		body{
			


			background:#fafafa;
		}

		h1, h2, h3, p, small{
			font-family: 'Roboto', sans-serif;
		}

		.div_main{
			width: 60%;
			margin: 50px auto;
		}

	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="{% url 'inicio' %}">Imprimiendo3D</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
				 
					{% if user.is_authenticated %}
					<li class="nav-item"><a class="nav-link" href="{% url 'leerBlogs' %}#top">Lista de blogs</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'inbox' %}#top">Mis mensajes</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'editarPerfil' %}#top">Mi perfil</a></li>
					<p> Hola {{ user.username }}</p>
					<img src="{{ imagen }}" alt="">
					<a class="btn btn-danger" href="{% url 'logout' %}">Desloguearme</a>
					{% else %}
					<a class="btn btn-primary" href="{% url 'login' %}">Login</a>
					{% endif %}

				</ul>
			</div>
		</div>
	</nav>
	
	

	<div class="div_main">
		{% block contenedor %}
		
		{% endblock %}
	</div>

</body>
</html>

App3D/templates/App3D/detalleBlog.html
{% extends "App3D/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">Pagina {{ blog }}</h1>
{% endblock %}

{% block contenido_que_cambia %}
<h2>Oops no hay paginas aun</h2>



{% endblock %}

App3D/templates/App3D/editarPerfil.html
{% extends "App3D/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">EDITANDO USUARIO: {{ nombreusuario }}</h1>
{% endblock %}

{% block titulo2 %}
<p class="text-white-30 mb-4"><a class="btn btn-success" href="{% url 'agregarAvatar' %}">Mi Avatar</a></p> 

{% endblock %}

{% block contenido_que_cambia %}

<form action="{% url 'editarPerfil'  %}" method="POST"> {% csrf_token %}

    <table>
    
        {{ form.as_table }}
    
    </table>
    
    <input type="submit" value="MODIFICAR USUARIO">
    
    
    </form>

    {{ mensaje }}

{% endblock %}

App3D/templates/App3D/inbox.html
{% extends 'App3D/base.html' %}


{% block contenedor %}

<h1>
	Bienvenido {{user}} a tu inbox personal.
</h1>

{% for inbox in inbox %}
<div class="div_inbox">

	
	{% for second_user in inbox.canalusuario_set.all %}

		{% if second_user.usuario ==  request.user %}

		{% else %}

			<a href="{% url 'detailms' second_user.usuario.username %}">
				<p>
					{{second_user.usuario}}
				</p>
				<small>
					({{inbox.canalmensaje_set.count}}) Mensajes
				</small>
			</a>

		{% endif %}

	{% endfor %}

	{% if inbox.canalmensaje_set.count != 0 %}
		<div class="div_ms_inbox">
			
			{% with ultimo_mensaje=inbox.canalmensaje_set.last %}

				<p>
					Mensaje: {{ultimo_mensaje.texto}}
				</p>

				<p>
					Usuario: {{ultimo_mensaje.usuario}}
				</p>

			{% endwith %}
		</div>	
	{% else %}
		<h2>
			Mi inbox
		</h2>
	{% endif %}



</div>
{% empty %}

<h2>
	Inbox Vacio
</h2>

{% endfor %}


<style>
	
	.div_inbox{
		width: 90%;
		margin:10px auto;
		background: #fff;
		border-radius: 5px;
		border:1px solid #e6e6e6;
		padding: 5px;
	}

</style>
		
{% endblock %}

App3D/templates/App3D/inicio.html
{% extends "App3D/padre.html" %}

{% load static %}


{% block titulo %}
<h2 class="fw-bolder mb-4 mt-5">Sobre nosotros</h2>
{% endblock %}

{% block imagenPrincipal %}
<figure class="mb-4"><img class="img-fluid rounded" src="{% static 'App3D/assets/bg-masthead.jpg' %}" alt="..." /></figure>
{% endblock %}



{% block titulo2 %}
<h4 class="mb-5"> {{ mensaje }} </h4>
{% endblock %}

{% block contenido_que_cambia %}

{% endblock %}


{% block parrafoInicio %}
    <p class="fs-5 mb-4">Este es un blog sobre impresión 3D, creado por entusiastas de la tecnología.
     Encontrarás información útil y actual, incluyendo reseñas de impresoras y consejos para hacer tus propios diseños.</p>
    <h2 class="fw-bolder mb-4 mt-5">Nuestro objetivo</h2>
    <p class="fs-5 mb-4">Nuestro objetivo es convertirnos en un recurso confiable y de confianza para todos los amantes de la impresión 3D, ya sean principiantes o profesionales. Creemos que la impresión 3D tiene el potencial de revolucionar la forma en que producimos y consumimos bienes, y esperamos contribuir a su creciente adopción a nivel mundial. Si eres un aficionado a la impresión 3D o simplemente estás interesado en conocer más sobre esta tecnología, ¡esperamos que encuentres nuestro blog útil y divertido de leer!</p>

{% endblock %}





{% block quiza %}
<div class="card bg-light">
<div class="card-body">
<!-- Comment form-->
<form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
<!-- Comment with nested comments-->
<div class="d-flex mb-4">
    <!-- Parent comment-->
    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
    <div class="ms-3">
        <div class="fw-bold">Commenter Name</div>
        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
        <!-- Child comment 1-->
        <div class="d-flex mt-4">
            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
            <div class="ms-3">
                <div class="fw-bold">Commenter Name</div>
                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
            </div>
        </div>
        <!-- Child comment 2-->
        <div class="d-flex mt-4">
            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
            <div class="ms-3">
                <div class="fw-bold">Commenter Name</div>
                When you put money directly to a problem, it makes a good headline.
            </div>
        </div>
    </div>
</div>
 <!-- Single comment-->
 <div class="d-flex">
    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
    <div class="ms-3">
        <div class="fw-bold">Commenter Name</div>
        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
    </div>
</div>
</div>
{% endblock %}



{% block bloque1 %}
<div class="card mb-4">
    <div class="card-header">
        <br>
        <h4>Nuestras normativas</h4>

        
    </div>
    <div class="card-body">
        <div class="row">
            <p>A pesar de que apoyamos el código abierto y la libertad de información, necesitamos que te registres para poder seguir unas normas de convivencia en el sitio.<br><br> Al registrarte, también podrás acceder a nuestra lista de blogs y disfrutar de todo lo que tenemos para ofrecer. ¡Gracias por tu comprensión y esperamos verte pronto en nuestro sitio!<p>
        </div>
    </div>
</div>

{% endblock %}






{% block bloque2 %}
<div class="card mb-4">
    <div class="card-header">
        <h4>Novedades</h4>
    </div>
    <div class="card-body">
        <p>¿Cómo funciona una impresora 3D de hormigón?<p>
            <figure class="mb-4"><img class="img-fluid rounded" src="{% static 'App3D/assets/concreto.jpg' %}" alt="..." /></figure>
        </div>
</div>
{% endblock %}



{% block tema %}
<div class="text-muted fst-italic mb-2">Blog creado por Andrés Kim</div>
<a class="badge bg-secondary text-decoration-none link-light" href="#!">Impresión 3D</a>
<a class="badge bg-secondary text-decoration-none link-light" href="#!">Diseño y tecnología</a>
{% endblock %}

App3D/templates/App3D/leerBlogs.html
{% extends "App3D/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">Lista de blogs</h1>
{% endblock %}

{% block contenido_que_cambia %}
<h2>LISTADO DE BLOGS</h2>
<ul>

    {% for blog in listaBlogs %}
    <li>{{ blog.Tema }} {{ blog.Material }} - {{ blog.Escala }}
    
    <a href="{% url 'detalleBlog' blog.id %}"style="color: blue;">Leer más</a>
    </li>

    {% endfor %}


</ul>
<h3>{{ mensaje }}</h3>

{% endblock %}

App3D/templates/App3D/listaBlogs.html
{% extends "App3D/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">ESTE TITULO VIENE DE PROFESORES!!</h1>
{% endblock %}

{% block contenido_que_cambia %}

<form action="{% url 'listaBlogs' %}" method="POST"> {% csrf_token %}

    <table>
    
        {{ form.as_table }}
    
    </table>
    
    <input type="submit" value="ENVIAR PROFE">
    
    
    </form>

{% endblock %}

App3D/templates/App3D/login.html
{% extends "App3D/padre.html" %}

{% load static %}


{% block titulo %}
<h2 class="fw-bolder mb-4 mt-5">Sobre nosotros</h2>
{% endblock %}

{% block imagenPrincipal %}
<figure class="mb-4"><img class="img-fluid rounded" src="{% static 'App3D/assets/bg-masthead.jpg' %}" alt="..." /></figure>
{% endblock %}



{% block titulo2 %}
<h4>Para loguearte aqui!</h4>
{% endblock %}

{% block contenido_que_cambia %}
<h2 class="text-white-75 mb-4">Log In</h2>
<form action="{% url 'login'  %}" method="POST"> {% csrf_token %}

    <table>
    
        {{ form.as_table }}
    
    </table>
    
    <input type="submit" value="INGRESAR">
    
    
    </form>

    {{ mensaje }}

    <hr class="divider divider-light" />
<p class="text-white-30 mb-4">No estas registrado? Registrate <a href="{% url 'register' %}"style="color: blue;">aqui</a></p> 

{% endblock %}


{% block parrafoInicio %}
    <p class="fs-5 mb-4">Este es un blog sobre impresión 3D, creado por entusiastas de la tecnología.
     Encontrarás información útil y actual, incluyendo reseñas de impresoras y consejos para hacer tus propios diseños.</p>
    <h2 class="fw-bolder mb-4 mt-5">Nuestro objetivo</h2>
    <p class="fs-5 mb-4">Nuestro objetivo es convertirnos en un recurso confiable y de confianza para todos los amantes de la impresión 3D, ya sean principiantes o profesionales. Creemos que la impresión 3D tiene el potencial de revolucionar la forma en que producimos y consumimos bienes, y esperamos contribuir a su creciente adopción a nivel mundial. Si eres un aficionado a la impresión 3D o simplemente estás interesado en conocer más sobre esta tecnología, ¡esperamos que encuentres nuestro blog útil y divertido de leer!</p>

{% endblock %}





{% block quiza %}
<div class="card bg-light">
<div class="card-body">
<!-- Comment form-->
<form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
<!-- Comment with nested comments-->
<div class="d-flex mb-4">
    <!-- Parent comment-->
    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
    <div class="ms-3">
        <div class="fw-bold">Commenter Name</div>
        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
        <!-- Child comment 1-->
        <div class="d-flex mt-4">
            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
            <div class="ms-3">
                <div class="fw-bold">Commenter Name</div>
                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
            </div>
        </div>
        <!-- Child comment 2-->
        <div class="d-flex mt-4">
            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
            <div class="ms-3">
                <div class="fw-bold">Commenter Name</div>
                When you put money directly to a problem, it makes a good headline.
            </div>
        </div>
    </div>
</div>
 <!-- Single comment-->
 <div class="d-flex">
    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
    <div class="ms-3">
        <div class="fw-bold">Commenter Name</div>
        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
    </div>
</div>
</div>
{% endblock %}



{% block bloque1 %}
<div class="card mb-4">
    <div class="card-header">
        <br>
        <h4>Nuestras normativas</h4>

        
    </div>
    <div class="card-body">
        <div class="row">
            <p>A pesar de que apoyamos el código abierto y la libertad de información, necesitamos que te registres para poder seguir unas normas de convivencia en el sitio.<br><br> Al registrarte, también podrás acceder a nuestra lista de blogs y disfrutar de todo lo que tenemos para ofrecer. ¡Gracias por tu comprensión y esperamos verte pronto en nuestro sitio!<p>
        </div>
    </div>
</div>

{% endblock %}






{% block bloque2 %}
<div class="card mb-4">
    <div class="card-header">
        <h4>Novedades</h4>
    </div>
    <div class="card-body">
        <p>¿Cómo funciona una impresora 3D de hormigón?<p>
            <figure class="mb-4"><img class="img-fluid rounded" src="{% static 'App3D/assets/concreto.jpg' %}" alt="..." /></figure>
        </div>
</div>
{% endblock %}



{% block tema %}
<div class="text-muted fst-italic mb-2">Blog creado por Andrés Kim</div>
<a class="badge bg-secondary text-decoration-none link-light" href="#!">Impresión 3D</a>
<a class="badge bg-secondary text-decoration-none link-light" href="#!">Diseño y tecnología</a>
{% endblock %}

App3D/templates/App3D/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}     
           
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Imprimiendo3D - Blog de noticias</title>
        <!-- Favicon-->
        <link rel="icon" type="image/png" href="{% static 'App3D/assets/Icono.png' %}">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'App3D/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inicio' %}">Imprimiendo3D</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                     
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'leerBlogs' %}#top">Lista de blogs</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'inbox' %}#top">Mis mensajes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'editarPerfil' %}#top">Mi perfil</a></li>
                        <p> Hola {{ user.username }}</p>
                        <img src="{{ imagen }}" alt="">
                        <a class="btn btn-danger" href="{% url 'logout' %}">Desloguearme</a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">

                            </h1>
                            <!-- Post meta content-->
                            
                            <!-- Post categories-->
                            {% block tema %}
                           
                            {% endblock %}
                        </header>
                            {% block titulo %}

                            {% endblock %}
                            
                            {% block imagenPrincipal %}

                            {% endblock %}

                        
                        <!-- Post content-->
                        <section class="mb-5">
                            {% block parrafoInicio %}
                            
                            
                            {% endblock %}
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">

                           
                                {% block quiza %}

                                {% endblock %}


                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">
                            {% block titulo2 %}

                            {% endblock %}
                        </div>
                        <div class="card-body">
                            <div class="input-group">
                                {% block contenido_que_cambia %}
            
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    {% block bloque1 %}

                    {% endblock %}
                    <!-- Side widget-->
                    {% block bloque2 %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright © 2022 Andrés Kim.<br> Todos los derechos reservados.</p> </p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

App3D/templates/App3D/register.html
{% extends "App3D/padre.html" %}

{% load static %}

{% block titulo2 %}
<p>Registrate</p>
{% endblock %}

{% block contenido_que_cambia %}

<form action="{% url 'register'  %}" method="POST"> {% csrf_token %}

    <table>
    
        {{ form.as_table }}
    
    </table>
    
    <input type="submit" value="CREAR USUARIO">
    
    
    </form>

    {{ mensaje }}

{% endblock %}